Fixed class types for the request
deepgram/deepgram-python-sdk pull request #96
Opened 2023-06-22 20:33 UTC by SaarthShah

Fixed types for the PrerecordedOptions(TranscriptionOptions, total=False) class.
Added another layer of testing for the summary returned within TranscriptionResults.

2023-06-22 22:39 UTC, lukeocodes requested changes
oops it shouldn't have the node package files 🤣

2023-06-22 22:42 UTC, lukeocodes requested changes

2023-06-22 22:42 UTC, lukeocodes commented on deepgram/_types.py
> +    summarize: Union[int, str]
also this is bool|str not int|str

2023-06-23 15:18 UTC, SandraRodgers approved these changes

2023-06-23 15:19 UTC, merged